#!/usr/bin/env bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

latest=$(github-latest obsidianmd/obsidian-releases)

sudo curl -L "https://github.com/obsidianmd/obsidian-releases/releases/download/${latest}/Obsidian-${latest}.AppImage" -o /usr/local/bin/obsidian
sudo chmod +x /usr/local/bin/obsidian